// =============================================================================
// src/types/index.ts
//
// Central type barrel.
//
// database.types.ts is generated by the Supabase CLI:
//   npx supabase gen types typescript --project-id <ref> > src/types/database.types.ts
// Do not manually edit that file — re-run the command after every schema change.
//
// This barrel re-exports the generated types plus hand-crafted domain helpers.
// =============================================================================

// ── Generated Supabase types ─────────────────────────────────────────────────
export type {
  Json,
  Database,
  Tables,
  TablesInsert,
  TablesUpdate,
  Enums,
  CompositeTypes,
} from './database.types';

// ── Convenient row-type aliases ───────────────────────────────────────────────
// Use Tables<'flights'> etc. directly from @supabase/supabase-js convention,
// or import these named aliases for readability.
import type { Tables as T } from './database.types';

export type FlightRow     = T<'flights'>;
export type SeatRow       = T<'seats'>;
export type BookingRow    = T<'bookings'>;
export type PassengerRow  = T<'passengers'>;
export type RescheduleRow = T<'reschedules'>;

// ── Domain enums (literal union types matching CHECK constraints in SQL) ─────
export type FlightStatus  = 'scheduled' | 'boarding' | 'departed' | 'cancelled';
export type SeatClass     = 'economy' | 'business' | 'first';
export type BookingStatus = 'confirmed' | 'rescheduled' | 'cancelled';

// ── Composite / helper types ──────────────────────────────────────────────────

/** A flight enriched with its associated seat list */
export type FlightWithSeats = FlightRow & {
  seats: SeatRow[];
};

/** A booking enriched with all related data needed for display */
export type BookingWithDetails = BookingRow & {
  flight: FlightRow;
  seat: SeatRow;
  passengers: PassengerRow[];
};
